name: Deploy Front a Neubox

on:
  push:
    branches:
      - main  # Se activa cuando subes cambios a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Obtener cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ— Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: âš™ï¸ Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: ğŸ“¦ Instalar dependencias y compilar
        run: |
          pnpm install
          pnpm build

      - name: ğŸš€ Subir archivos a Neubox via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          local-dir: ./dist/  # Sube solo lo que estÃ¡ en dist
          server-dir: public_html/  # AsegÃºrate que sea la ruta correcta